<?php
$config = array();
$config['secure'] = true;
$config['password'] = "user1, user2, user3, user4";
$config['admin'] = "admin";
$config['homepage'] = "vinaget.us";
$config['download_prefix'] = "vinaget_";
$config['download_suffix'] = "";
$config['limitMBIP'] = 100 * 1024;
$config['ttl'] = 6 * 60;
$config['limitPERIP'] = 10;
$config['ttl_ip'] = 1;
$config['max_jobs_per_ip'] = 100;
$config['max_jobs'] = 500;
$config['max_load'] = 50;
$config['max_size_default'] = 2048;
$config['file_size_limit'] = 2050;
$config['title'] = "[color=blue] download [/color]";
$config['colorfilename'] = "green";
$config['colorfilesize'] = "red";
$config['listfile'] = true;
$config['showlinkdown'] = true;
$config['showdirect'] = true;
$config['redirectdl'] = false;
$config['bbcode'] = true;
$config['longurl'] = true;
$config['privatefile'] = false;
$config['privateip'] = false;
$config['checkacc'] = true;
$config['checklinksex'] = false;
$config['rename'] = true;
$config['delete'] = true;
$config['display_error'] = false;
$config['ziplink_ads'] = false;
$config['api_ads1'] = "";
$config['api_ads2'] = "";
$config['api_ads3'] = "";
$config['tinyurl_each_ziplink'] = false;
$config['tinyurl'] = false;
$config['badword'] = "porn, sex, hentai, xxx, jav";
$config['language'] = "english";
$config['skin'] = "default";
$config['cbox_url'] = "http://www4.cbox.ws/box/index.php?boxid=4270578&boxtag=vinaget31";
$config['display_error'] = false;
$config['hide_plugins_col'] = false;
$config['debrid_mode'] = false;
?>